Belen add logs to git checkout
arromer/github-fetch-buildkite-plugin pull request #37
Opened 2021-01-28 00:55 UTC by belugarciafava

We are having issues while trying to checkout the repository see: https://buildkite.com/canva-org/web-test-base/builds/337662#b59f36a3-4637-4248-98f3-524915b29371
Github support got back to us asking to add
```
GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push -u origin master
```
to git operations to have more logging info

Not sure how to deploy the checkout plugin or add a new version of it

2021-01-28 01:03 UTC, arromer approved these changes

2021-01-28 01:04 UTC, arromer commented
to release new version of the plugin we need to update all the occurrences of the old commit with the new commit once this is merged into master, in canva and infrastructure repos

2021-01-28 01:04 UTC, uri-canva requested changes
This is going to be extremely verbose, can you pipe it to a file, upload the file via `buildlkite-agent artifact upload` and then print out a message in the logs? Also double check what the performance impact of tracing is, we might not want to have it always enabled.

2021-01-28 01:05 UTC, arromer commented on hooks/checkout
>      timeout "${GIT_REMOTE_TIMEOUT}" git fetch -v --no-tags origin "${BUILDKITE_BRANCH}" || exit_code=$?
maybe we should add it here too?

2021-02-04 06:44 UTC, danjuv commented
Moving this to #41 so I can test this before merging into master

2021-02-04 06:44 UTC, closed without merging