Change to correct dir when copying from s3 on mac os agents
arromer/github-fetch-buildkite-plugin pull request #86
Opened 2022-12-22 02:37 UTC by yanw-canva

## Context
When used on mac os agents, buildkite default working dir isn't in the format of `<github_org_name>__<repo_name>` but rather in the format of `<buildkite_org_name>/<pipeline_name>`. 
Whereas the archive file extracted from s3 goes into `<github_org_name>__<repo_name>` dir.

## Change
So change into `<github_org_name>__<repo_name>` dir explicitly after extracting archive

2022-12-27 22:54 UTC, arromer requested changes
This has been solved in other agents by having an environment hook that makes sure the checkout dir is in the correct format before cloning/checking out the repo

See for example:
https://github.com/Canva/infrastructure/blob/bf1077f4fd5e39aa9cf407058f9ec7d2a205d398/common/ci-agent/ami-base/bootstrap/init_buildkite_hooks.sh#L18-L33

This also makes sure that there is only one copy of each repo in the agent for all pipelines instead of one copy per pipeline.

Would this be a valid approach for macos agents?

2022-12-27 23:59 UTC, yanw-canva commented
Yep, I can change the macos agents AMI to do the same things, it'll be quite time consuming though. 
I'm a newbie so I don't know if there's a use case of build step that does not use this plugin and not wanting to have the checkout path overriden.
Please let me know if changing the agent's environment hook is the way you want me to go.

2022-12-28 00:08 UTC, arromer commented
yes, updating the environment hook is preferred, even if we don't use this plugin it will improve the checkout times by having only one clone per repo as opposed to one clone per pipeline (if you run multiple pipelines in these agents you will end up with multiple clones of the same repo)

2022-12-28 00:13 UTC, yanw-canva commented
👍 No worries, will do so. Thanks!

2022-12-28 00:13 UTC, closed without merging